Feature profile in depth fe
kuri-team/poios-app pull request #15
Opened 2021-09-02 08:08 UTC by Linh-0v0

1. Omit Timetable in my-profile and tutor-profile.
2. Change 'book appointment', 'send message' button into 'Status: Available/Busy'.
3. Form in my-profile is able to save user input when editing account info (except upload image, subject tag).
4. Big save button is replaced with each individual mini save buttons.
5. Update CSS responsive.

2021-09-02 08:36 UTC, rider3458 approved these changes

2021-09-02 11:08 UTC, doanyennhi requested changes
- For my-profile page: There should be some feedback for SAVE button
Otherwise, everything is great!

2021-09-03 15:19 UTC, doanyennhi approved these changes

2021-09-03 15:34 UTC, lacnham approved these changes

2021-09-04 01:54 UTC, merged